[package]
name = "skycalc"
version = "0.0.3"
edition = "2021"

[dependencies]
chrono = "0.4.40"
fltk ={ version = "1.5.2", features = ["fltk-bundled"] }
fltk-evented = "0.5.3"
fltk-theme = "0.7.4"
libm = "0.2.11"
serde = { version = "1.0.218", features = ["derive"] }
serde_yaml = "0.9.34"
