observer:
  name: Tromso observatory
  longitude: 19.0
  latitude: 69.669998
  elevation: 0
  timezone: 1

time: 2024-12-11 12:00:00 # local time

environment:
  pressure: 1020
  temperature: 25
  humidity: 45

constraints:
  min_altitude: 30  # in deg above horizon
  max_altitude: 80  # in deg above horizon
  min_size: 10  # in arc minutes
  max_size: 300  # in arc minutes
  moon_separation: 45  # in degrees
  use_darkness: true
  # object needs to be within the constraints for at least 50% of darkness
  frac_observable_time: 50
  # maximum number of targets within threshold to calculate
  max_targets: 60

others:
  target_list: targets/OpenNGC
  type_filter: # e.g. Galaxy, Nebula
  output_dir: output
