observatory_name: Piracaia - SP - Brazil
observation_date: 20241028 # yyyy-mm-dd, dd/mm/yyyy, dd-mm-yyyy or yyyymmdd
target_list: targets/OpenNGC
type_filter: # e.g. Galaxy, Nebula
output_dir: output

location:
  longitude: 046d 30m W # <->DDD.DD, DDD° MM' SS" <E/W> or DDDd MMm SSs <E/W>
  latitude: 23d 06m S # <->DD.DD, DDD° MM' SS" <N/S> or DDDd MMm SSs <N/S>
  elevation: 780
  timezone: -3.0

environment:
  pressure: 1022
  temperature: 25
  humidity: 70

constraints:
  altitude_constraint_min: 30  # in deg above horizon
  altitude_constraint_max: 80  # in deg above horizon
  size_constraint_min: 10  # in arc minutes
  size_constraint_max: 300  # in arc minutes
  moon_separation_min: 45  # in degrees
  use_darkness: true
  # object needs to be within the constraints for at least 50% of darkness
  fraction_of_time_observable_threshold: 50
  # maximum number of targets to calculate
  max_number_within_threshold: 60


