observer:
  name: Piracaia - SP - Brazil
  longitude: 046d 30m W # <->DDD.DD, DDD° MM' SS" <E/W> or DDDd MMm SSs <E/W>
  latitude: 23d 06m S # <->DD.DD, DDD° MM' SS" <N/S> or DDDd MMm SSs <N/S>
  elevation: 780
  timezone: -3 # (-/+)HH:MM, (-/+)HH.HH

time: 2024-12-11 12:00:00 # UTC

environment:
  pressure: 1020
  temperature: 25
  humidity: 45

constraints:
  min_altitude: 30  # in deg above horizon
  max_altitude: 80  # in deg above horizon
  min_size: 10  # in arc minutes
  max_size: 300  # in arc minutes
  moon_separation: 45  # in degrees
  use_darkness: true
  # object needs to be within the constraints for at least 50% of darkness
  frac_observable_time: 50
  # maximum number of targets within threshold to calculate
  max_targets: 60

others:
  target_list: targets/OpenNGC
  type_filter: # e.g. Galaxy, Nebula
  output_dir: output
